name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Run compile
        run: csbt pullRemoteCache headerCheck +compile pushRemoteCache bintrayRemoteCacheCleanOld
        env:
          BINTRAY_REMOTE_CACHE_USER: ${{ secrets.BINTRAY_REMOTE_CACHE_USER }}
          BINTRAY_REMOTE_CACHE_PASS: ${{ secrets.BINTRAY_REMOTE_CACHE_PASS }}
